image: golang:latest

stages:
  - build

build:
  stage: build
  script:
    - export GOPATH=/build/go
    - export SRC=$GOPATH/src/gitlab.com/dbehnke74/updatecheck
    - mkdir -p $SRC
    - export PATH=$GOPATH/bin:$PATH
    - cp -R * $SRC
    - cd $SRC
    - GOOS=linux GOARCH=amd64 go test
    - mkdir updatecheck
    - GOOS=linux GOARCH=amd64 go build cmd/updatecheck/main.go; cp main updatecheck/updatecheck_linux_amd64
    - GOOS=windows GOARCH=amd64 go build cmd/updatecheck/main.go; cp main updatecheck/updatecheck_windows_amd64
    - GOOS=osx GOARCH=amd64 go build cmd/updatecheck/main.go; cp main updatecheck/updatecheck_darwin_amd64
    - cd updatecheck
    - cp ../bin/* .
    - cp -R ../software .
  tags:
    - docker
  artifacts:
    paths:
     - updatecheck
