image: golang:latest

stages:
  - build

build:
  stage: build
  script:
    - GOOS=linux GOARCH=amd64 go test gitlab.com/dbehnke74/updatecheck/software
    - mkdir updatecheck
    - GOOS=linux GOARCH=amd64 go build -mod vendor; cp updatecheck updatecheck/updatecheck_linux_amd64
    - GOOS=windows GOARCH=amd64 go build -mod vendor; cp updatecheck updatecheck/updatecheck_windows_amd64
    - GOOS=darwin GOARCH=amd64 go build -mod vendor; cp updatecheck updatecheck/updatecheck_darwin_amd64
    - cd updatecheck
    - cp -R ../definitions .
  tags:
    - docker
  artifacts:
    paths:
     - updatecheck
