image: golang:latest

stages:
  - build

build:
  stage: build
  script:
    - GOOS=linux GOARCH=amd64 go test -mod vendor gitlab.com/dbehnke74/updatecheck/software
    - mkdir updatecheck_release
    - GOOS=linux GOARCH=amd64 go build -mod vendor; cp updatecheck updatecheck_release/updatecheck_linux_amd64
    - GOOS=windows GOARCH=amd64 go build -mod vendor; cp updatecheck updatecheck_release/updatecheck_windows_amd64
    - GOOS=darwin GOARCH=amd64 go build -mod vendor; cp updatecheck updatecheck_release/updatecheck_darwin_amd64
    - cd updatecheck_release
    - cp -R ../definitions .
    - ./updatecheck_linux_amd64 results ./definitions
    - ./updatecheck_linux_amd64 query results.json firefoxesr mac current_version
    - ./updatecheck_linux_amd64 query results.json firefoxesr mac download_url
    - ./updatecheck_linux_amd64 query results.json thunderbird mac current_version
    - ./updatecheck_linux_amd64 query results.json thunderbird mac download_url
    - ./updatecheck_linux_amd64 query results.json virtualbox mac current_version
    - ./updatecheck_linux_amd64 query results.json virtualbox mac download_url
    - ./updatecheck_linux_amd64 query results.json oraclejavajdk mac current_version
    - ./updatecheck_linux_amd64 query results.json oraclejavajdk mac download_url
    - ./updatecheck_linux_amd64 query results.json libreoffice-enterprise mac current_version
    - ./updatecheck_linux_amd64 query results.json libreoffice-enterprise mac download_url
    - ./updatecheck_linux_amd64 query results.json gimp mac current_version
    - ./updatecheck_linux_amd64 query results.json gimp mac download_url
    - ./updatecheck_linux_amd64 query results.json adobeflashplayer mac current_version
    - ./updatecheck_linux_amd64 query results.json adobeflashplayer mac download_url

  tags:
    - docker
  artifacts:
    paths:
     - updatecheck_release
